### ISSUE TITLE
E-03 of 5CC missing

### ISSUE THREAD

**Issue by AmossGuy** [Mnstrman06/Celeste-Modded-Randomizer#3]
I’m guessing you originally made the config before the randomizer implemented warps?
I think it should look something like this:
```yaml
- Room: "E-03"
  Holes:
  - Side: Right
    Idx: 0
    Kind: inout
  InternalEdges:
  - CustomWarp: true
    ReqOut:
      Dashes: one
      Difficulty: hard
```
